prefix ops: <https://w3id.org/semanticarts/ns/ontology/operators/> 
prefix ver: <https://w3id.org/semanticarts/ns/ontology/versioning/> 
PREFIX sh: <http://www.w3.org/ns/shacl#>

# Finds all cases WHERE a version dependency requirement is not met 
   SELECT DISTINCT (?focus AS ?dependent) ?dependency (CONCAT(?requirement, '. ',?errorMessage) AS ?message)
   
   WHERE {
    VALUES (?depType ?depText) { 
      (ops:hasValueEqualTo "=")
      (ops:hasValueLessThan "<")
      (ops:hasValueLessOrEqualTo "<=")
      (ops:hasValueGreaterThan ">")
      (ops:hasValueGreaterOrEqualTo ">=")
    }
    ?focus ver:dependsOn [ ver:isVersionRangeOf ?dependency ; ?depType [ ver:uniqueText ?depValue ] ] ;
           ver:hasVersionNumber [ ver:uniqueText ?focusVersion ]
           .
    ?dependency ver:hasVersionNumber [ ver:uniqueText ?depVersion ] .
    BIND(xsd:double(REPLACE(?depValue, '^([0-9]+\\.[0-9]+).*','$1')) AS ?bn1)  
    BIND(xsd:double(REPLACE(?depValue, '^[0-9]+\\.[0-9]+(\\.*)','$1')) AS ?bn2)
    BIND(floor(?bn1*1000)+?bn2 AS ?depValueNum)

    BIND(xsd:double(REPLACE(?depVersion, '^([0-9]+\\.[0-9]+).*','$1')) AS ?vn1)  
    BIND(xsd:double(REPLACE(?depVersion, '^[0-9]+\\.[0-9]+(\\.*)','$1')) AS ?vn2)
    BIND(floor(?vn1*1000)+?vn2 AS ?depVersionNum)

    BIND(COALESCE(
      IF(?depType=ops:hasValueEqualTo && ?depValueNum != ?depVersionNum, 'not equal to', ?NoMismatch),
      IF(?depType=ops:hasValueLessThan && ?depValueNum <= ?depVersionNum, 'greater or equal to', ?NoMismatch),
      IF(?depType=ops:hasValueLessOrEqualTo && ?depValueNum < ?depVersionNum, 'greater than', ?NoMismatch),
      IF(?depType=ops:hasValueGreaterThan && ?depValueNum >= ?depVersionNum, 'less or equal to', ?NoMismatch),
      IF(?depType=ops:hasValueGreaterOrEqualTo && ?depValueNum > ?depVersionNum, 'less than', ?NoMismatch)
    ) AS ?mismatch)

    FILTER(BOUND(?mismatch))

    BIND(CONCAT(
      'The actual version ', ?depVersion, ', is ', ?mismatch,
      ' the specified version ', ?depValue
    ) AS ?errorMessage)

    ?focus skos:prefLabel ?focusLabel .
    ?dependency skos:prefLabel ?dependencyLabel .
        BIND(CONCAT('Version ', ?focusVersion, ' of ', ?focusLabel, ' requires the version of ', ?dependencyLabel, ' to be ', ?depText, ' ', ?depValue) AS ?requirement)

  } order by ?focus 
  