prefix ops: <https://w3id.org/semanticarts/ns/ontology/operators/>
prefix ver: <https://w3id.org/semanticarts/ns/ontology/versioning/>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX sh: <http://www.w3.org/ns/shacl#>

# Finds all cases where a dependency specified via owl:imports
# conflicts with the versioning dependency definition
# Return result as a SHACL report
CONSTRUCT {
  ?report a sh:ValidationReport ;
            sh:conforms false ;
            sh:result [
              a sh:ValidationResult ;
                sh:resultSeverity sh:Violation ;
                sh:focusNode ?focus ;
                sh:resultPath ?depType ;
                sh:value ?dependency ;
                sh:resultMessage ?message ;
                sh:sourceConstraintComponent <urn:validation:Version> ;
            ]
            .
}
WHERE {
  { SELECT DISTINCT ?focus ?depType ?dependency ?message WHERE {
    VALUES ?depType {
      ops:hasValueEqualTo
      ops:hasValueLessThan
      ops:hasValueLessOrEqualTo
      ops:hasValueGreaterThan
      ops:hasValueGreaterOrEqualTo
    }

    # Parse <base-uri>X.x.x from owl:imports
    ?focus owl:imports ?dependencyVersionIRI .
    FILTER(REGEX(STR(?dependencyVersionIRI), '.*[0-9]+\\.[0-9]+\\.[0-9]+$'))
    BIND(REPLACE(STR(?dependencyVersionIRI), '.*([0-9]+\\.[0-9]+\\.[0-9]+)$', '$1') AS ?dependencyVersion)
    BIND(URI(REPLACE(STR(?dependencyVersionIRI), '(.*)[0-9]+\\.[0-9]+\\.[0-9]+$', '$1')) AS ?dependency)

    ?focus ver:dependsOn [ ver:isVersionRangeOf ?dependency ; ?depType [ ver:uniqueText ?depValue ] ] ;
           ver:hasVersionNumber [ ver:uniqueText ?focusVersion ]
           .
    BIND(xsd:double(REPLACE(?depValue, '^([0-9]+\\.[0-9]+).*','$1')) AS ?bn1)
    BIND(xsd:double(REPLACE(?depValue, '^[0-9]+\\.[0-9]+(\\.*)','$1')) AS ?bn2)
    BIND(floor(?bn1*1000)+?bn2 AS ?boundaryNum)

    BIND(xsd:double(REPLACE(?dependencyVersion, '^([0-9]+\\.[0-9]+).*','$1')) AS ?vn1)
    BIND(xsd:double(REPLACE(?dependencyVersion, '^[0-9]+\\.[0-9]+(\\.*)','$1')) AS ?vn2)
    BIND(floor(?vn1*1000)+?vn2 AS ?versionNum)

    BIND(COALESCE(
      IF(?depType=ops:hasValueEqualTo && ?boundaryNum != ?versionNum, 'not equal to', ?NoMismatch),
      IF(?depType=ops:hasValueLessThan && ?boundaryNum <= ?versionNum, 'greater or equal to', ?NoMismatch),
      IF(?depType=ops:hasValueLessOrEqualTo && ?boundaryNum < ?versionNum, 'greater than', ?NoMismatch),
      IF(?depType=ops:hasValueGreaterThan && ?boundaryNum >= ?versionNum, 'less or equal to', ?NoMismatch),
      IF(?depType=ops:hasValueGreaterOrEqualTo && ?boundaryNum > ?versionNum, 'less than', ?NoMismatch)
    ) AS ?mismatch)

    FILTER(BOUND(?mismatch))

    BIND(CONCAT(
      'Imported version ', ?dependencyVersion, ' is ', ?mismatch,
      ' specified version ', ?depValue
    ) AS ?message)
  }}
  BIND(URI(CONCAT('urn:validation:report:', STR(NOW()))) AS ?report)
}